# yaml-language-server: $schema=./dist/rubocop.json
%YAML 1.1
---
inherit_from:
  - "https://www.goodcop.style/base.yml"

AllCops:
  TargetRubyVersion: 3.4

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
